### ISSUE TITLE
Readme File errors

### ISSUE THREAD

**Issue by KeithDColes** [mrpjevans/zxscanner#1]
The readme file is in error.  It is stating what I believe to be an old version of GPIO data pins to keyboard data lines.

I believe they should be as per the article in Magpi (photo attached)

Regards,

Keith
![20190317_142308](https://user-images.githubusercontent.com/48650907/54493032-85ac6080-48c3-11e9-844c-4dd10655daf6.jpg)

**Comment by mrpjevans** [comment]
Oh yes, correct, they refer to the original project. I've added the MagPi version in. Thanks for bringing it to my attention.

**Comment by KeithDColes** [comment]
Good call.  It may be worth noting in the read me that the .py code is aligned to the magpi config.  If they wire it up as per the original blog wiring if wont work due to the data lines being misaligned..
